language: ruby
script: "bundle exec rspec spec"
before_install: "gem update --system"
env:
  - CI=true SINATRA_VERSION=1.4
  - CI=true SINATRA_VERSION=2.0
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9
  - rbx-3
cache: bundler
sudo: false
matrix:
  allow_failures:
    - rvm: jruby-9
    - rvm: rbx-3
dist: trusty
